import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";
import MenuShow from "./MenuShow";
import PapularDishes from "./PapularDishes";
import ResturantChains from "./ResturantChains";
import Slider from "./Slider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">x
            <body className={inter.className}>
                <Navbar />
                {/* <Slider/> */}
                <MenuShow/>
                {children}
                <ResturantChains/>
                <PapularDishes/>
                <Footer/>
            </body>
        </html>
    );
}
